### PR TITLE
Merge swagger2.0 branch into master - bump to 2.0.0-rc1

### PR DESCRIPTION
**Pull request by analogue**
- This takes the swagger2.0 feature branch and merges it into master
- The last four commits are the only additional changes
- Major version bump to 2.0.0-rc1

### CODE REVIEW

**Comment by striglia** [comment]
Let's make sure we wrap up the current release (basically just bumping and tagging to 1.5.0 properly) before doing 2.0.0.

I'd also like to make sure we add at least a rough migration guide to the documentation. If it's short, we can inline in the 2.0.0 changelog, otherwise it is probably worth a separate page. 

It seems likely there are significant complications associated with 1.2 and 2.0 coexisting in pyramid_swagger. I'm thinking incompatible configuration choices and so on. Let's document those wherever we explain the migration process from 1.x to 2.0.0

**Comment by dnephin** [comment]
Closes #94

@striglia I haven't heard any problems with v1.5.0-rc2, but I'm not sure how widely used it is.  Do you know of anything outstanding? Should we just tag the same sha as v1.5.0 ?

We can always create a 1.5.x bug release branch if we need to fix anything critical, where an upgrade isn't possible.

**Comment by striglia** [comment]
Same here, I haven't heard bad news from 1.5.0. That said, if we merge this into master, we won't have any chances to release 1.5.x. Any clue how best to reconcile those competing goals?

**Comment by analogue** [comment]
@striglia as @dnephin said, we can always branch from the 1.5.0 sha and push out a 1.5.x if needed

**Comment by striglia** [comment]
Makes sense to me. So we'll have a long-lived 1.2 branch (`swagger12_stable` or something like that) that continues to get small bugfixes and releases, and that allows master to progress forward, eventually removing 1.2 support in a 3.0 release?

**Comment by johnschultz** [comment]
There is the currently outstanding File handling bug rc2. This accidentally
bit us the other day when we upgraded too far. Not sure if its worth
delaying the release over though.

**Comment by analogue** [comment]
@striglia sounds like a plan

**Comment by analogue** [comment]
Things I have in the pipeline for the PR
- rename release to 2.0.0-rc1
- add docs for migration from 1.2 to 2.0

**Comment by striglia** [comment]
@johnschultz yeah given that I haven't heard any immediate plans for fixing that, let's delay it to a bugfix release after 1.5.0

**Comment by striglia** [comment]
Cool. 1.5.0 is released on github and https://pypi.python.org/pypi/pyramid_swagger. We can branch off that tag the next time we need to do any 1.2-only releases.

**Comment by analogue** [comment]
@striglia Added migration guide.  wrt "incompatible configuration choices", there are none afaik but that story may change after I get some more real world testing in with this release candidate.

**Comment by striglia** [comment]
Migration guide looks good...a couple notes there. Otherwise I think the RC plan is a solid one. We can release it once documentation is shored up and see if it actually works :)

**Comment by dnephin** [comment]
lgtm, and it looks like travis is happy now as well.

If you're good with the docs @striglia let's get this merged

**Comment by striglia** [comment]
I'm game. Merge away and we can fix up any issues in another RC or the actual release itself

**Comment by dnephin** [comment]
I'll tag master with the rc number

**Pull request merged**
