### PR TITLE
Py3X support

### PR DESCRIPTION
**Pull request by msander**

### CODE REVIEW

**Comment by msander** [comment]
docs are failing because https://helloreverb.com/developers/swagger is dead

**Comment by striglia** [comment]
Thanks for the PR!

You can definitely just replace the reverb link with http://swagger.io/getting-started/. I'm a little surprised using bravado-core isn't giving us any py3 issues....but I guess the proof is in the CI run.

Resolves #139

**Comment by msander** [comment]
Bravado-core seems to support python 3 since version 1.1.0 (2015-06-25).
Nevertheless I haven't used it yet. I'm building my first project with swagger on python 3 and pyramid.
Any specific issues you have in mind which need to be looked at carefully?

**Comment by striglia** [comment]
Nah, I am probably mis-remembering how this came up in the first place. I say we let the tests be the judge and we can always put out a bugfix release if that doesn't do it.

**Pull request merged**
