### PR TITLE
This adds back support for pyramid 1.6

### PR DESCRIPTION
**Pull request by sontek**

### CODE REVIEW

**Comment by sontek** [comment]
Pyramid 1.6 changed the default status code for unknown errors to `520`.  So I just updated the tests to allow that. The failing pep8 and docs wasn't caused by this PR, master fails as well.

**Comment by djeebus** [comment]
Thanks @sontek! I was hoping this would show up soon =)

**Comment by djeebus** [comment]
#154 shows that this fix causes the tests to pass.

**Comment by sontek** [comment]
@striglia I updated this with a cleaner fix.  The pep8 and docs are failing because of existing problems in master but it looks like @djeebus has sent PRs to fix all of them.

**Pull request merged**
