### PR TITLE
make flake8 compliant

### PR DESCRIPTION
**Pull request by tomster**
just some cosmetics to make the test go green again :-)

### CODE REVIEW

**Comment by striglia** [comment]
Curious that flake8 wasn't unhappy on Jenkins. Looks like this runs afoul of [80 char limits](https://travis-ci.org/striglia/pyramid_swagger/jobs/146421758) but some parentheses should let the line break happen and keep flake8+pep8 happy.

Out of curiosity, what traceback did flake8 give you originally?

**Comment by tomster** [comment]
weird that they now fail on jenkins: here's the failure i got when running tox locally:

`tests/tween_test.py:269:9: E123 closing bracket does not match indentation of opening bracket's line
tests/acceptance/yaml_test.py:56:12: E126 continuation line over-indented for hanging indent
tests/acceptance/yaml_test.py:62:12: E126 continuation line over-indented for hanging indent
`

**Comment by striglia** [comment]
Ah, over-indentation. Also probably fixable by just un-indenting the original multi-line comparisons once. 

FWIW I think your original Travis run was hitting some downtime on their end https://twitter.com/traviscistatus/status/756213817462231040.

**Comment by sjaensch** [comment]
This was done by my recent change where I ran flake8 on all files.

**Pull request closed without merging**
